# Generated by Django 4.1.2 on 2022-12-13 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LittleLemonDRF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_customer', to=settings.AUTH_USER_MODEL)),
                ('delivery_crew', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='delivery_crew', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(related_name='ORDER_products', to='LittleLemonDRF.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_status', models.BooleanField(default=True)),
                ('orders', models.ManyToManyField(blank=True, null=True, related_name='his_orders', to='LittleLemonDRF.orders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverycrew', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ManyToManyField(related_name='order_menu', to='LittleLemonDRF.menuitem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
