# Generated by Django 4.1.2 on 2022-12-13 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LittleLemonDRF', '0003_orders_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryprofile',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='his_orders', to='LittleLemonDRF.orders'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='delivery_crew',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_crew', to=settings.AUTH_USER_MODEL),
        ),
    ]
